"""Shared global state for the EduMAS pipeline.

The StudyState object is created in main.py and threaded through every
LangGraph node. Each agent reads what it needs and writes its own field;
no field is overwritten silently.
"""
from __future__ import annotations

from typing import List, TypedDict


class PracticeQuestion(TypedDict):
    """A single practice Q/A pair generated by the QuestionGeneratorAgent."""
    question: str
    answer: str


class StudyState(TypedDict, total=False):
    """The global state passed between every agent in the pipeline.

    Fields are populated cumulatively as the workflow progresses:
        AssessmentAgent      -> sets `weak_topic`
        GapAnalystAgent      -> sets `knowledge_brief`
        QuestionGeneratorAgent -> sets `practice_questions`
        StudyPlannerAgent    -> sets `study_plan` and `study_plan_path`

    `logs` is a running execution trace that every node appends to.
    """
    quiz_path: str
    student_input: str
    weak_topic: str
    knowledge_brief: str
    practice_questions: List[PracticeQuestion]
    study_plan: str
    study_plan_path: str
    study_plan_pdf_path: str
    logs: List[str]


def init_state(quiz_path: str) -> StudyState:
    """Create a fresh StudyState pointing at the given quiz file."""
    return StudyState(
        quiz_path=quiz_path,
        student_input="",
        weak_topic="",
        knowledge_brief="",
        practice_questions=[],
        study_plan="",
        study_plan_path="",
        study_plan_pdf_path="",
        logs=[],
    )
